import { Suspense } from "react";
import "./styles/globals.css";
import dynamic from "next/dynamic";
import Loading from "./components/Loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GlobalComponent = dynamic(() => import("./components/Global"));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <GlobalComponent dom={children}></GlobalComponent>
        </Suspense>
      </body>
    </html>
  );
}
